baseURL = "http://example.org/"
languageCode = "en-us"
title = "温之来的个人网站"
theme = "hugo-theme-notrack"
newContentEditor = "nvim"
mainSections = ["blog"]
# disqusShortname = "example"
paginate = 4

[params]
  author = "温之来"
  siteHeading = "WEN" # defaults to author
  favicon = "1596713672968.jpeg" # Adds a small icon next to the page title in a tab
  showBlogLatest = true
  mainSections = ["blog"]
  showTaxonomyLinks = true
  nBlogLatest = 3 # number of blog post om the home page
  blogLatestHeading = "我的文章"

  [params.social]
    github = "hoist-wen"
    email = "wen170732349@163.com"
    steam = "76561198321401746"
    zhihu = "jiao-cha-zuo-biao-de-xing-chen-42"
    bilibili = "8360955"
    rss = "rss won't use the value you give it so you can put anything here"

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"
